.\"
.\" @DEC_COPYRIGHT@
.\"
.\"
.\" HISTORY
.\" Revision 1.1.2.3  1996/11/19  12:22:14  Cathy_Page
.\" 	Updated references to DECtalk documentation to reflect correct name.
.\" 	Updated application desc to include reference to DECtalk software.
.\" 	[1996/11/19  12:20:17  Cathy_Page]
.\"
.\" Revision 1.1.2.2  1996/02/15  19:47:28  Krishna_Mangipudi
.\" 	Moved from man 3
.\" 	[1996/02/15  19:46:35  Krishna_Mangipudi]
.\" 
.\" $EndLog$
.\"
.TH ACLOCK 1dtk "" "" "" "DECtalk" ""
.SH NAME
aclock \- Talking clock
.SH SYNOPSIS
.PP
.B aclock
.RB [ \-h ]
.RI [ # ]
.SH FLAGS
.Tp
.BR \-h
Displays the command line parameter list
.SH PARAMETERS
.TP
.I #
where \*L#\*O is the interval in minutes:
.RS
.TP
5
every five minutes
.TP
15
every fifteen minutes
.TP
30
on the hour and half hour
.TP
60
on the hour
.RE
.SH DESCRIPTION
.PP
aclock announces the time of the day using DECtalk Software.
.SH EXAMPLES
.PP
aclock 5  -  Announces time of the day every five minutes.
.SH RELATED INFORMATION
.PP
.BR dectalk (1dtk),
.BR audiocontrol (1mms),
.BR mmeserver (1mms)
.PP
DECtalk Software Programmer's Guide
