.\"
.\" @DEC_COPYRIGHT@
.\"
.\"
.\" HISTORY
.\" Revision 1.1.2.3  1996/11/19  12:22:15  Cathy_Page
.\" 	Updated references to DECtalk documentation to reflect correct name.
.\" 	[1996/11/19  12:20:20  Cathy_Page]
.\"
.\" Revision 1.1.2.2  1996/02/21  14:52:06  Krishna_Mangipudi
.\" 	Initial Creation
.\" 	[1996/02/21  14:51:55  Krishna_Mangipudi]
.\" 
.\" $EndLog$
.\"
.TH EMACSPEAK 1dtk "" "" "" "DECtalk" ""
.SH NAME
emacspeak \- Speech-enables emacs
.SH DESCRIPTION
.PP
.B emacspeak
is an emacs subsystem
that provides speech feedback using synthesized speech.
The basic concepts used by Emacspeak are simple;
all Emacs cursor movement commands
as well as the various input-output functions
are adapted to provide speech feedback.
Hence, a user can use Emacs as they normally would;
emacspeak works behind the scenes to give audio feedback
in addition to updating the screen.
.SH ACCESSING EMACSPEAK
.PP
To access emacspeak under Tru64 UNIX,
you must choose to install emacspeak during DECtalk Software runtime kit installation.
.PP
All emacspeak files end up in the directory
.BR /usr/opt/DTKRTnnn/emacspeak ,
where nnn denotes the DECtalk Software version,
at the end of installation.
.PP
To use emacspeak after runtime kit installation,
change directory (\fBcd\fP) over to
.B /usr/opt/DTKRTnnn/emacspeak/Macros
and type:
.BR "make help" .
Follow the instructions to complete installing emacspeak.
.SH RELATED INFORMATION
.PP
.BR dectalk (1dtk),
.BR emacs (1),
.PP
.B emacspeak-README.txt
- In /usr/opt/DTKRTnnn/emacspeak/docs/ascii
.PP
.B emacspeak.ps
- In /usr/opt/DTKRTnnn/emacspeak/docs/postscript
.PP
DECtalk Software Programmer's Guide
.PP
DECtalk Software Installation Guide
