.\"
.\" @DEC_COPYRIGHT@
.\"
.\"
.\" HISTORY
.\" Revision 1.1.2.3  1996/11/19  12:22:20  Cathy_Page
.\" 	Updated references to DECtalk documentation to reflect correct name.
.\" 	Updated application desc to include reference to DECtalk software.
.\" 	[1996/11/19  12:20:26  Cathy_Page]
.\"
.\" Revision 1.1.2.2  1996/02/15  19:47:35  Krishna_Mangipudi
.\" 	Moved from man 3
.\" 	[1996/02/15  19:46:44  Krishna_Mangipudi]
.\" 
.\" $EndLog$
.\"
.\"
.TH SPEAK 1dtk "" "" "" "DECtalk" ""
.SH NAME
speak \- Simple text editor that can read using DECtalk Software
.SH SYNOPSIS
.PP
.B speak
[\fB-device\fP \fI#\fP]
[\fB-encoding\fP \fI#\fP]
[\fB-file\fP \fIfilename\fP]
[\fB-help\fP]
.SH FLAGS
.TP
.BI -device #
Selects the audio device (0 or 1).
.TP
.BI -encoding #
Selects the encoding, as follows:
.RS
.TP
1
PCM, 16 bit Mono 11.025KHz format
.TP
2
PCM, 8 bit Mono 11.025KHz format
.TP
3
MULAW, 8 bit Mono 8KHz format
.RS
.TP
.BI -file filename
Specifies a file for speak to use.
.TP
.BI -help
Displays help text.
.SH DESCRIPTION
.PP
The \fBspeak\fP application is provided in the DECtalk Software kit.
(For Tru64 UNIX,
it is bundled with the runtime kit).
The application demonstrates the capabilities of DECtalk Software.
.SH RELATED INFORMATION
.PP
.BR dectalk (1dtk),
.BR audiocontrol (1mms),
.BR mmeserver (1mms)
.PP
DECtalk Software Programmer's Guide
