/* XPM */
static char * dtk_speak_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 6 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s iconColor1	m black	c black",
"X	c #808080808080",
"o	s iconColor6	m white	c yellow",
"O	s iconColor7	m white	c cyan",
"+	c #000000008080",
/* pixels */
"  ......................     .............      ",
"XX.  o  o  o  o  o  o  o   ..             ...   ",
"XX.  o  o  o  o  o  o  o   ..             ...   ",
"XX.oo..................   .                  .. ",
"XX.  .  O  O  O  O  O  O..                     .",
"XX.  .  O  O  O  O  O  O..                     .",
"XX.oo.OO OO OO OO OO OO .. ++   +   ++   +     .",
"XX.  .  O  O  O  O  O  O.. ++ ++ ++      +  +  .",
"XX.  .  O  O  O  O  O  O.. ++ ++ ++      +  +  .",
"XX.oo.OO OO OO OO OO OO .. ++ ++ ++ +++   +++  .",
"XX.  .  O  O  O  O  O  O..                     .",
"XX.  .  O  O  O  O  O  O..                     .",
"XX.oo.OO OO OO OO OO OO ..                     .",
"XX.  .  O  O  O  O  O  O..                   .. ",
"XX.  .  O  O  O  O  O  O..                   .. ",
"XX.oo.OO OO OO OO OO OO OO.           ......... ",
"XX.  .  O  O  O  O  O  O..   .........O  O      ",
"XX.  .  O  O  O  O  O  O..   .........O  O      ",
"XX.   OO OO OO OO OO OO ..... OO OO OO OO .. .. ",
"XX   ............O  O  O  O  O  O  O  O  O..o.. ",
"XX   ............O  O  O  O  O  O  O  O  O..o.. ",
"   ..            .OO OO OO OO OO OO OO OO .. .. ",
"   ..             .....O  O  O  O  O  O  O..o.. ",
"   ..             .....O  O  O  O  O  O  O..o.. ",
"  .                  .. OO OO OO OO OO OO .. .. ",
"  .  +     +  +     .  O  O  O  O  O  O  O..o.. ",
"  .  +     +  +     .  O  O  O  O  O  O  O..o.. ",
"  .  +  +      ++   .   OO OO OO OO OO OO .. .. ",
"  .  +++   +   ++   .  O  O  O  O  O  O  O..o..X",
"  .  +++   +   ++   .  O  O  O  O  O  O  O..o..X",
"  .                 .  ..................... ..X",
"  .                 .  o  o  o  o  o  o  o  o..X",
"  .                 .  o  o  o  o  o  o  o  o..X",
"  .                 .  ........................ ",
"   ..             .. XXXXXXXXXXXXXXXXXXXXXXX    ",
"   ..             .. XXXXXXXXXXXXXXXXXXXXXXX    ",
"   ................. .......................    ",
"        X  X  X  X  X  .  .  .  .  .  .   ...   ",
"        X  X  X  X  X  .  .  .  .  .  .   ...   ",
"      .. .. .. .. .. .. .. .. .. .. .. ..   .   ",
"  .  .  .  .  .  .  .  .  .  .  .  .  .  .   .. ",
"  .  .  .  .  .  .  .  .  .  .  .  .  .  .   .. ",
"XX.............................................X",
"XX.  o  o  o  o  o  o  o  o  o  o  o  o  o  o..X",
"XX.  o  o  o  o  o  o  o  o  o  o  o  o  o  o..X",
"XX.............................................X",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "};
