/* XPM */
static char * dtk_speak_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s iconColor1	m black	c black",
"X	c #808080808080",
"o	s iconColor6	m white	c yellow",
"O	s iconColor7	m white	c cyan",
"+	c #000000008080",
/* pixels */
" ...............   .........    ",
"X. o o o o o o o  .         ..  ",
"X.o............  .            . ",
"X. . O O O O O O.              .",
"X.o.O O O O O O . +  +  +  +   .",
"X. . O O O O O O. + + +    + + .",
"X.o.O O O O O O . + + + ++  ++ .",
"X. . O O O O O O.              .",
"X.o.O O O O O O .              .",
"X. . O O O O O O.             . ",
"X.o.O O O O O O O.       ...... ",
"X. . O O O O O O.  ......O O    ",
"X.  O O O O O O ... O O O O . . ",
"X  ........O O O O O O O O O.o. ",
"  .        .O O O O O O O O . . ",
"  .         ...O O O O O O O.o. ",
" .            . O O O O O O . . ",
" . +   + +   . O O O O O O O.o. ",
" . + +    +  .  O O O O O O . . ",
" . ++  +  +  . O O O O O O O.o.X",
" .           . .............. .X",
" .           . o o o o o o o o.X",
" .           . ................ ",
"  .         . XXXXXXXXXXXXXXX   ",
"  ........... ...............   ",
"     X X X X X . . . . . .  ..  ",
"    . . . . . . . . . . . .  .  ",
" . . . . . . . . . . . . . .  . ",
"X..............................X",
"X. o o o o o o o o o o o o o o.X",
"X..............................X",
"  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX "};
