//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by skipdemo.rc
//
#define IDD_SKIPDEMO_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDI_PLAY                        129
#define IDI_STOP                        130
#define IDC_SKIPAHEAD                   1000
#define IDC_SKIPBACK                    1001
#define IDC_TIMESLIDE                   1002
#define IDC_EDITBOX                     1004
#define IDC_STOP                        1005
#define IDC_PLAY                        1006
#define IDC_TIME                        1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
