/* This sorry piece of code was made because I couldn't on earth
   figure out how the code generated by lex and the one generated by yacc (bison)
   could please share a variable that could be modified by either of the. 
   Here we are dealing with the problem of knowning where in the parsing 
   of a file (line no and column number) we are when parsing fails.

   Author: Reiner Wilhelms-Tricarico

   This code needs to be linked with the bison and lex generated table c files.
   see Makefile.
*/

typedef 
struct _lex_position{
  int line;
  int col;
  int prevcol;
} lex_position;

static lex_position lexpos = {1,1,0};

void set_lex_column(int col)
{
  lexpos.col = col;
}

void set_lex_line(int lin)
{
  lexpos.line=lin;
}

void nextlexline()
{
  lexpos.line+=1;
  lexpos.col=0;
}

void movelexcolumn(int inc)
{
  lexpos.prevcol=lexpos.col;
  lexpos.col += inc;
}

void reset_lex_pos()
{
  lexpos.line=1;
  lexpos.col=1;
  lexpos.prevcol=1;
}

int lex_column()
{
  return lexpos.col;
}

int lex_lastcol()
{
  return lexpos.prevcol;
}

int lex_line()
{
  return lexpos.line;
}
