.TH "TextToSpeechGetFeatures" 3dtk "" "" "" "DECtalk" ""
.SH Name
.PP
\fBTextToSpeechGetFeatures\fP \-
Retrieves information about DECtalk Software features.
.SH Syntax
.EX
DWORD \fBTextToSpeechGetFeatures\fP (void)
.EE
.SH Description
.PP
This function 
retrieves information, in the form of a bitmask, about the features of
DECtalk Software.
.PP 
If the DECtalk Multi-Language (ML) engine is running, the ML bit is set to
TRUE, as well as any feature bits returned from DECtalk.
.PP
Future implementation may involve calling TextToSpeechSelectLang() to select
the language for which to retrieve information.
.SH Return Values
.PP
This function returns a value of type DWORD, which is a bitmask
of features supported by DECtalk.  The value returned is maskable to the
list of values supplied in the header file TTSFEAT.H.
.SH Example
.EX
BOOL is_dectalk_ml (unsigned int language_handle) {
    unsigned long int feats;
    
    TextToSpeechSelectLang (NULL, language_handle);
    feats = TextToSpeechGetFeatures();
    if (feats & TTS_FEATS_MULTILANG) {
        printf ("DECtalk ML installed and running.\en");
        return TRUE;
    }
    printf ("Multi-language DECtalk not found.\en");
    return FALSE;
}
.EE
