.\"
.\" @DEC_COPYRIGHT@
.\"
.\"
.\" HISTORY
.\" Revision 1.1.2.3  1996/02/15  22:52:55  Krishna_Mangipudi
.\" 	Added Synopsis
.\" 	[1996/02/15  22:34:43  Krishna_Mangipudi]
.\"
.\" Revision 1.1.2.2  1996/02/15  20:12:10  Krishna_Mangipudi
.\" 	Moved to man3
.\" 	[1996/02/15  20:06:26  Krishna_Mangipudi]
.\"
.\" $EndLog$
.\"
.TH "TextToSpeechUnloadUserDictionary" 3dtk "" "" "" "DECtalk" ""
.SH Name
.PP
\fBTextToSpeechUnloadUserDictionary\fP \-
Unloads a user dictionary.
.SH Syntax
.EX
MMRESULT \fBTextToSpeechUnloadUserDictionary\fP (LPTTS_HANDLE_T \fIphTTS\fP)
.EE
.SH Parameters
.IP "LPTTS_HANDLE_T \fIphTTS\fP" 20
Specifies an opened text-to-speech handle.
.SH Description
.PP
This function unloads a user dictionary. You must unload any previously
loaded dictionary before you can load a new one. That is, only one user
dictionary can be loaded at a time.
.PP
A user dictionary is created using the User Dictionary Build tool.
.SH Return Values
.PP
This function returns a value of type MMRESULT. The value is zero
if the function is successful. The return value is one of the
following constants:
.PP
.TS
tab(@);
lfR lw(4i)fR .
.sp 4p
Constant@Description
.sp 6p
MMSYSERR_NOERROR
@T{
Normal successful completion (zero).
T}
.sp
MMSYSERR_INVALHANDLE
@T{
The text-to-speech handle was invalid.
T}
.sp
.TE
.PP
.SH See Also
.PP
Dictionary Functions (Linux and UNIX) (DECtalk Software Programmer's Guide)
.PP
\fITextToSpeechLoadUserDictionary\fP(3dtk)
