.\"
.\" @DEC_COPYRIGHT@
.\"
.\"
.\" HISTORY
.\" Revision 1.1.2.3  1996/02/15  22:52:29  Krishna_Mangipudi
.\" 	Added Synopsis
.\" 	[1996/02/15  22:33:58  Krishna_Mangipudi]
.\"
.\" Revision 1.1.2.2  1996/02/15  20:11:07  Krishna_Mangipudi
.\" 	Moved to man3
.\" 	[1996/02/15  20:05:06  Krishna_Mangipudi]
.\"
.\" $EndLog$
.\"
.TH "TextToSpeechGetLanguage" 3dtk "" "" "" "DECtalk" ""
.SH Name
.PP
\fBTextToSpeechGetLanguage\fP \-
See TextToSpeechEnumLangs().
.SH Warning
.PP
The TextToSpeechGetLanguage() function is not supported for DECtalk Software
Version 4.5 or higher.  Use of this call may cause unpredictable operation and
application linking errors.
.PP
This function has been replaced by TextToSpeechGetCaps().
Multi-language programming is supported by the functions
TextToSpeechEnumLangs(), TextToSpeechStartLang(), TextToSpeechSelectLang(),
and TextToSpeechCloseLang().
