.TH "TextToSpeechTyping" 3dtk "" "" "" "DECtalk" ""
.SH Name
.PP
\fBTextToSpeechTyping\fP \-
Speaks a single letter as quickly as possible, aborting any previously queued
speech.
.SH Syntax
.EX
void \fBTextToSpeechTyping\fP (LPTTS_HANDLE_T \fIphTTS\fP,
                        char \fIcLetter\fP)
.EE
.SH Parameters
.IP "LPTTS_HANDLE_T \fIphTTS\fP" 20
Specifies an opened text-to-speech handle.
.IP "char \fIcLetter\fP" 20
Specifies the letter to speak.
.SH Description
.PP
This function speaks a single letter as quickly as possible, aborting any
previously queued speech.  The function is somewhat slower if
TextToSpeechSpeak() was called since the last TextToSpeechTyping() or
TextToSpeechReset() call.
.PP
This function is primarily useful with Access32 versions of DECtalk Software.
The function exists in non-Access32 versions, but is not fast.
.PP
TextToSpeechTyping() should be called only when synthesizing directly to an
audio device (not to memory or to a file).
.SH See Also
.PP
\fITextToSpeechReset\fP(3dtk),
\fITextToSpeechSpeak\fP(3dtk)
