.\"
.\" @DEC_COPYRIGHT@
.\"
.\"
.\" HISTORY
.\" Revision 4.6 7/26/1999 Jeff Staples
.\"     Minor changes
.\"
.\" $EndLog$
.\"
.TH "TextToSpeechTyping" 3dtk "" "" "" "DECtalk" ""
.SH Name
.PP
\fBTextToSpeechTyping\fP \-
Speaks a single letter as quickly as possible, aborting any previously queued
speech.
.SH Syntax
.EX
void \fBTextToSpeechTyping\fP (LPTTS_HANDLE_T \fIphTTS\fP,
                        char \fIcLetter\fP)
.EE
.SH Parameters
.IP "LPTTS_HANDLE_T \fIphTTS\fP" 20
Specifies a text-to-speech handle identifying the opened text-to-speech
handle.
.IP "char \fIcLetter\fP" 20
Specifies the character to speak.
.SH Description
.PP
This function speaks a single letter as quickly as possible, aborting any
previously queued speech.  The function is somewhat slower if
TextToSpeechSpeak() was called since the last TextToSpeechTyping() or
TextToSpeechReset() call.
.PP
The call is useful primarily with Access32 versions of DECtalk Software.
The call exists in non-Access32 versions, but is not particularly fast.
.PP
TextToSpeechTyping() should be called only when the application is
synthesizing directly to an
audio device, not to memory or to a file.
.SH See Also
.PP
\fITextToSpeechReset\fP(3dtk),
\fITextToSpeechSpeak\fP(3dtk)
