.\"
.\" @DEC_COPYRIGHT@
.\"
.\"
.\" HISTORY
.\" Revision 1.1.2.3  1996/02/15  22:52:53  Krishna_Mangipudi
.\" 	Added Synopsis
.\" 	[1996/02/15  22:34:41  Krishna_Mangipudi]
.\"
.\" Revision 1.1.2.2  1996/02/15  20:12:05  Krishna_Mangipudi
.\" 	Moved to man3
.\" 	[1996/02/15  20:06:24  Krishna_Mangipudi]
.\"
.\" $EndLog$
.\"
.TH "TextToSpeechSync" 3dtk "" "" "" "DECtalk" ""
.SH Name
.PP
\fBTextToSpeechSync\fP \-
Blocks until all previously queued text is processed.
.SH Syntax
.EX
MMRESULT \fBTextToSpeechSync\fP (LPTTS_HANDLE_T \fIphTTS\fP)
.EE
.SH Parameters
.IP "LPTTS_HANDLE_T \fIphTTS\fP" 20
Specifies an opened text-to-speech handle.
.SH Description
.PP
This function blocks until all previously queued text is
processed. TextToSpeechSync() automatically resumes audio output if the
text-to-speech system was placed in a paused state by
TextToSpeechPause().
.SH Return Values
.PP
This function returns a value of type MMRESULT. The value is zero
if the function is successful. The return value is one of the
following constants:
.PP
.TS
tab(@);
lfR lw(4i)fR .
.sp 4p
Constant@Description
.sp 6p
MMSYSERR_NOERROR
@T{
Normal successful completion (zero).
T}
.sp
MMSYSERR_ERROR
@T{
Unable to complete queued text.
T}
.sp
MMSYSERR_INVALHANDLE
@T{
The text-to-speech handle was invalid.
T}
.sp
.TE
.PP
.SH See Also
.PP
\fITextToSpeechPause\fP(3dtk)
