.TH "TextToSpeechVersionEx" 3dtk "" "" "" "DECtalk" ""
.SH Name
.PP
\fBTextToSpeechVersionEx\fP \-
Returns information about the currently running version of DECtalk Software.
.SH Syntax
.EX
DWORD \fBTextToSpeechVersionEx\fP (LPVERSION_INFO \fI*ver\fP)
.EE
.SH Parameters
.IP "LPVERSION_INFO \fI*ver\fP" 20
Returns the address of a pointer to an array of characters containing
version information.  The VERSION_INFO structure contains the following
information:
.EX
DWORD   StructSize;
DWORD   StructVersion;
WORD    DLLVersion;
WORD    DTalkVersion;
LPSTR   VerString;
LPSTR   Language;
DWORD   Features;
.EE
.SH Description
.PP
This function returns information about the currently running version of
DECtalk Software in a VERSION_INFO structure.
.SH Return Values
.PP
This function returns a value of type DWORD indicating the size of the
VERSION_INFO structure that was returned to the caller. The return value is zero if the call is not successful.  No other error information is available.
.SH Example
.EX
BOOL IsDECtalkMLInstalled(void) {
    LPVERSION_INFO verinfo;
    
    TextToSpeechVersionEx (&verinfo);
    if (ver->Features & TTS_FEATS_MULTILANG) return TRUE;
    return FALSE;
}
.EE
