//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dictool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DICTOOL_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_WORDNUMBER                  135
#define IDD_ADVSEARCH                   137
#define IDR_PRI_ACCEL                   138
#define IDC_SEARCHWORD                  1000
#define IDC_CURRENTWORD                 1001
#define IDC_SEARCH_BUTTON               1002
#define IDC_NEXT_WORD                   1003
#define IDC_PREVIOUS_WORD               1004
#define IDC_PHONEMES                    1005
#define IDC_FC_ADJ                      1006
#define IDC_FC_ADV                      1007
#define IDC_ADDWORD                     1008
#define IDC_FC_ART                      1009
#define IDC_FC_AUX                      1010
#define IDC_FC_BE                       1011
#define IDC_FC_BEV                      1012
#define IDC_FC_CONJ                     1013
#define IDC_FC_ED                       1014
#define IDC_FC_HAVE                     1015
#define IDC_FC_ING                      1016
#define IDC_FC_NOUN                     1017
#define IDC_FC_POS                      1018
#define IDC_FC_PREP                     1019
#define IDC_FC_PRON                     1020
#define IDC_FC_SUBCONJ                  1021
#define IDC_FC_THAT                     1022
#define IDC_FC_TO                       1023
#define IDC_FC_VERB                     1024
#define IDC_FC_WHO                      1025
#define IDC_FC_NEG                      1026
#define IDC_FC_INTER                    1027
#define IDC_FC_REF                      1028
#define IDC_FC_PART                     1029
#define IDC_FC_FUNC                     1030
#define IDC_FC_CONT                     1031
#define IDC_FC_CHARACTER                1032
#define IDC_FC_REFR                     1033
#define IDC_HOMOGRAPH                   1034
#define IDC_DELETEWORD                  1035
#define IDC_PRIORITY                    1036
#define IDC_FC_DET                      1037
#define IDC_COMMIT                      1038
#define IDC_WORDCOUNT                   1041
#define IDC_RESTORE_WORD                1045
#define IDC_STATIC_PHONEMES             1046
#define IDC_STATIC_HOMOGRAPH            1047
#define IDC_STATIC_PRIORITY             1048
#define IDC_SEARCHTYPE                  1049
#define IDC_STATIC_DICTWORD             1050
#define IDC_SEARCHCLASS2                1050
#define IDC_STATIC_SEARCH               1051
#define IDC_STATIC_SEARCH_TYPE          1052
#define IDC_PRONOUNCE                   1053
#define IDC_STATIC_ARPAPHONES           1054
#define IDC_ENTER_WORD_NUMBER           1055
#define IDC_STATIC_WARNING              1056
#define IDC_SEARCH_DIRECTION            1059
#define IDC_FC_NAME                     1060
#define IDC_AUTO_PRON                   1061
#define IDC_BUILDLIST                   1063
#define IDC_WORDTOMATCH                 1064
#define IDC_CLASSTOMATCH                1065
#define IDC_WORDSFOUND                  1066
#define IDC_ADVLIST                     1067
#define IDC_SAVELIST                    1068
#define IDC_PRI1                        1069
#define IDC_PRI2                        1070
#define IDC_STATIC_PRIORITYMATCH        1070
#define IDC_PRI3                        1071
#define IDC_PRIORITY_SEARCH             1071
#define IDC_PRI4                        1072
#define IDC_STATIC_PRIORITYTYPE         1072
#define IDC_PRI5                        1073
#define IDC_PRIORITY_TYPE_SEARCH        1073
#define IDC_PRI6                        1074
#define IDC_PRI7                        1075
#define IDC_PRI8                        1076
#define IDC_PRI9                        1077
#define IDC_COMBO1                      1078
#define IDC_HOMO_SEARCH                 1078
#define IDC_HOMOTOMATCH                 1079
#define ID_FILE_EXIT                    32774
#define ID_HELP_ABOUT                   32775
#define ID_EDIT_GOTOWORD                32777
#define ID_EDIT_AUTOADVANCE             32778
#define ID_LANGUAGE_USENGLISH           32779
#define ID_LANGUAGE_UKENGLISH           32780
#define ID_LANGUAGE_GERMAN              32781
#define ID_LANGUAGE_SPANISH             32782
#define ID_LANGUAGE_LATINAMERICAN       32783
#define ID_LANGUAGE_FRENCH              32784
#define ID_EDIT_ADVANCEDSEARCH          32785
#define ID_EDIT_SAVEADVANCEDLIST        32786
#define ID_EDIT_PRIORITYSETMODE         32787
#define ID_FILE_OPEN_AS_TEXT            32788
#define ID_EDIT_SORTDICTIONARY          32789
#define ID_EDIT_REMOVEDULPICATES        32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
