/******************************************************************************\
*       guidseg.cpp
*
*       This file initializes GUIDS for the Microsoft Speech API
*       NOTE: do not use Precompiled Headers to compile this file
*       due to the inclusion of initguid.h.
*
*       This code and information is provided "as is" without warranty
*       of any kind, either expressed or implied, including but not
*       limited to the implied warranties of merchantability and/or
*       fitness for a particular purpose.
*
*       Copyright (C) 1995 Microsoft Corporation.  All Rights Reserved.
*
\******************************************************************************/

/* 28apr97 ncs                                     */
/* This file in SAMPLES\TTSTEST is now obsolete.   */
/* Get the real guidseg.cpp file from sapi\src\api */