/*****************************************************************/
/* Speech.H - Header file to use the Microsoft Speech APIs.      */
/*****************************************************************/
/* This file has been gutted and now uses the speech.h in the    */
/*  work\rnd\microsoft directory                                 */
/*****************************************************************/
#include "..\..\..\microsoft\speech.h"

