/*****************************************************************************
* TtsEng.idl *
*------------*
*   Description:
*       This idl file is for the sample SAPI5 Text To Speech Engine.
*-----------------------------------------------------------------------------
*   Creation: 09/17/99
*  Copyright (c) Microsoft Corporation. All rights reserved.
*****************************************************************************/
//--- Import base idl
import "oaidl.idl";
import "ocidl.idl";
import "sapiddk.idl";

//=== Forward References ======================================================

//=== Constants ===============================================================

//=== Interface definitions ===================================================
typedef struct VOICEITEM
{
    LPCWSTR pText;
    ULONG   ulTextLen;
    ULONG   ulNumAudioBytes;
    BYTE*   pAudio;
} VOICEITEM;

#ifdef ENGLISH_US
//=== CoClass definitions =====================================================
[
	uuid(99EE9581-A4A6-11d1-BEB2-0060083E8376),
	version(1.0),
	helpstring("DECtalk Paul US 1.0 Type Library")
]
library DECTALKPAULUSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(99EE9580-A4A6-11d1-BEB2-0060083E8376),
		helpstring("DECtalkPaulUS Class")
	]
	coclass DECtalkPaulUS 
	{
		[default] interface ISpTTSEngine;
        interface ISpObjectWithToken;
	};
};
#endif
#ifdef SPANISH_SP
//=== CoClass definitions =====================================================
[
	uuid(99EE9583-A4A6-11d1-BEB2-0060083E8376),
	version(1.0),
	helpstring("DECtalk Paul SP 1.0 Type Library")
]
library DECTALKPAULSPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(99EE9582-A4A6-11d1-BEB2-0060083E8376),
		helpstring("DECtalkPaulSP Class")
	]
	coclass DECtalkPaulSP 
	{
		[default] interface ISpTTSEngine;
        interface ISpObjectWithToken;
	};
};
#endif
#ifdef SPANISH_LA
//=== CoClass definitions =====================================================
[
	uuid(99EE9585-A4A6-11d1-BEB2-0060083E8376),
	version(1.0),
	helpstring("DECtalk Paul LA 1.0 Type Library")
]
library DECTALKPAULLALib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(99EE9584-A4A6-11d1-BEB2-0060083E8376),
		helpstring("DECtalkPaulLA Class")
	]
	coclass DECtalkPaulLA 
	{
		[default] interface ISpTTSEngine;
        interface ISpObjectWithToken;
	};
};
#endif
#ifdef GERMAN
//=== CoClass definitions =====================================================
[
	uuid(99EE9587-A4A6-11d1-BEB2-0060083E8376),
	version(1.0),
	helpstring("DECtalk Paul GR 1.0 Type Library")
]
library DECTALKPAULGRLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(99EE9586-A4A6-11d1-BEB2-0060083E8376),
		helpstring("DECtalkPaulGR Class")
	]
	coclass DECtalkPaulGR 
	{
		[default] interface ISpTTSEngine;
        interface ISpObjectWithToken;
	};
};
#endif
#ifdef ENGLISH_UK
//=== CoClass definitions =====================================================
[
	uuid(99EE9589-A4A6-11d1-BEB2-0060083E8376),
	version(1.0),
	helpstring("DECtalk Paul UK 1.0 Type Library")
]
library DECTALKPAULUKLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(99EE9588-A4A6-11d1-BEB2-0060083E8376),
		helpstring("DECtalkPaulUK Class")
	]
	coclass DECtalkPaulUK 
	{
		[default] interface ISpTTSEngine;
        interface ISpObjectWithToken;
	};
};
#endif
#ifdef FRENCH
//=== CoClass definitions =====================================================
[
	uuid(99EE9591-A4A6-11d1-BEB2-0060083E8376),
	version(1.0),
	helpstring("DECtalk Paul FR 1.0 Type Library")
]
library DECTALKPAULFRLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(99EE9590-A4A6-11d1-BEB2-0060083E8376),
		helpstring("DECtalkPaulFR Class")
	]
	coclass DECtalkPaulFR 
	{
		[default] interface ISpTTSEngine;
        interface ISpObjectWithToken;
	};
};
#endif