.\"
.\" @DEC_COPYRIGHT@
.\"
.\"
.\" HISTORY
.\" Revision 1.1.2.3  1996/11/19  12:22:14  Cathy_Page
.\" 	Updated references to DECtalk documentation to reflect correct name.
.\" 	Updated application desc to include reference to DECtalk software.
.\" 	[1996/11/19  12:20:17  Cathy_Page]
.\"
.\" Revision 1.1.2.2  1996/02/15  19:47:28  Krishna_Mangipudi
.\" 	Moved from man 3
.\" 	[1996/02/15  19:46:35  Krishna_Mangipudi]
.\" 
.\" $EndLog$
.\"
.\" This manpage source uses rsml coding. 
.\"
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.TH aclock 1dtk "" "" "" "DECtalk" ""
.SH NAME
.PP
\*Laclock\*O \- Talking clock
.SH SYNOPSIS
.PP
.sS
\*Laclock\*O \*O[\*L-h #\*O]
.sE
.SH FLAGS
.PP
.VL 4m
.LI "\*L-h\*O"
Displays the command line parameter list
.LE
.SH PARAMETERS
.PP
.VL 4m
.LI "\*L#\*O"
.nf
where \*L#\*O is the interval in minutes:
5  - every five minutes
15 - every fifteen minutes
30 - on the hour and half hour
60 - on the hour
.fi
.LE
.SH DESCRIPTION
.PP
aclock announces the time of the day using DECtalk Software.
.SH EXAMPLES
.PP
aclock 5  -  Announces time of the day every five minutes.
.SH RELATED INFORMATION
.PP
\*Ldectalk\*O(1dtk), \*Laudiocontrol\*O(1mms), \*Lmmeserver\*O(1mms)
.PP
DECtalk Software Programmer's Guide
