/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for NT_APPS.HH
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_NT_APPS_Using_the_Program_Applets_to_Learn_DECtalk_Software_Basics 1001
#define IDH_NT_APPS_About_the_Sample_Applet 1002
#define IDH_NT_APPS_Starting_the_Sample_Applet_and_Opening_a_Text_File 1003
#define IDH_NT_APPS_To_start_the_Sample_Applet_and_open_a_text_file 1004
#define IDH_NT_APPS_To_speak_a_file_using_drag_and_drop 1005
#define IDH_NT_APPS_Inserting_Voice_Control_Commands_Syntax_Rules 1006
#define IDH_NT_APPS_Changing_Voice_Selections 1007
#define IDH_NT_APPS_DECtalk_Voices_and_Their_Associated_Values 1008
#define IDH_NT_APPS_Changing_DECtalk_Software_Voices 1009
#define IDH_NT_APPS_To_change_voices_using_the_Speaking_Voice_Menu 1010
#define IDH_NT_APPS_To_Change_Voices_Using_Voice_Control_Commands 1011
#define IDH_NT_APPS_Editing_a_Text_File_and_Changing_the_Speaking_Rate 1012
#define IDH_NT_APPS_To_edit_a_text_file_from_the_Sample_Applet 1013
#define IDH_NT_APPS_To_play_selected_text_from_the_Sample_Applet 1014
#define IDH_NT_APPS_To_change_the_speaking_rate_from_the_Sample_Applet 1015
#define IDH_NT_APPS_Components_of_the_User_Dictionary_Build_Tool 1016
#define IDH_NT_APPS_Overview_of_the_User_Dictionary_Build_Tool 1017
#define IDH_NT_APPS_Building_a_User_Dictionary 1018
#define IDH_NT_APPS_To_build_a_User_Dictionary 1019
#define IDH_NT_APPS_Saving_and_Compiling_the_Dictionary 1020
#define IDH_NT_APPS_To_save_and_compile_the_User_Dictionary 1021
#define IDH_NT_APPS_Using_the_DECtalk_Software_Speak_Applet1 1022
#define IDH_NT_APPS_Using_the_DECtalk_Software_Speak_Applet1 1023
#define IDH_NT_APPS_To_edit_and_play_text_from_the_DECtalk_Speak_Applet 1024
#define IDH_NT_APPS_To_change_the_speaking_rate_from_the_DECtalk_Speak_Applet 1025
#define IDH_NT_APPS_To_load_a_User_Dictionary_from_the_DECtalk_Speak_Applet 1026
#define IDH_NT_APPS_To_save_text_as_a_WAVE_file_from_the_DECtalk_Speak_Application 1027
#define IDH_NT_APPS_Running_DECtalk_Software_from_Other_Applications 1028
#define IDH_NT_APPS_Creating_a_Word_Macro 1029
#define IDH_NT_APPS_To_create_a_Word_Macro_and_associate_it_with_a_file_or_template 1030
#define IDH_NT_APPS_Associating_the_Macro_with_aTool_Bar_Button 1031
#define IDH_NT_APPS_To_associate_a_macro_with_a_tool_bar_button 1032
#define IDH_NT_APPS_Launching_and_Configuring_the_DECtalk_TTS_Server 1033
#define IDH_NT_APPS_To_launch_and_configure_the_DECtalk_Software_Text_to_Speech_Server 1034
#define IDH_NT_APPS_Speaking_Text_with_the_DECtalk_Software_TTS_Server 1035
#define IDH_NT_APPS_To_speak_text_with_the_DECtalk_TTS_Server 1036
#define IDH_NT_APPS_Using_the_Say_Command_Line_Applet 1037
#define IDH_NT_APPS_Help_Options 1038
#define IDH_NT_APPS_Output_Options 1039
#define IDH_NT_APPS_Input_Options 1040
#define IDH_NT_APPS_Dictionary_Options 1041
#define IDH_NT_APPS_Using_the_DECtalk_Software_Speak_Applet 1042
#define IDH_NT_APPS_Highlighting_Text_as_it_is_Spoken_Illustrated 1043
#define IDH_NT_APPS_To_highlight_text_as_it_is_spoken 1044
#define IDH_NT_APPS_allophone 1045
#define IDH_NT_APPS_applet 1046
#define IDH_NT_APPS_arpabet 1047
#define IDH_NT_APPS_clause_boundary 1048
#define IDH_NT_APPS_clause_mode 1049
#define IDH_NT_APPS_clause_terminator 1050
#define IDH_NT_APPS_comma_pause 1051
#define IDH_NT_APPS__DIC_file 1052
#define IDH_NT_APPS_emphatic_stress 1053
#define IDH_NT_APPS_falling_intonation 1054
#define IDH_NT_APPS_flush 1055
#define IDH_NT_APPS_heuristic 1056
#define IDH_NT_APPS_homograph 1057
#define IDH_NT_APPS_index_marker_flag 1058
#define IDH_NT_APPS_intonation 1059
#define IDH_NT_APPS_letter_mode 1060
#define IDH_NT_APPS_log_file 1061
#define IDH_NT_APPS_morpheme 1062
#define IDH_NT_APPS_period_pause 1063
#define IDH_NT_APPS_phoneme 1064
#define IDH_NT_APPS_phoneme_arpabet_command 1065
#define IDH_NT_APPS_phoneme_string 1066
#define IDH_NT_APPS_phonemicize 1067
#define IDH_NT_APPS_phonemic_mode 1068
#define IDH_NT_APPS_phonemic_transcription 1069
#define IDH_NT_APPS_phrase_boundary 1070
#define IDH_NT_APPS_pitch_control_symbols 1071
#define IDH_NT_APPS_primary_stress 1072
#define IDH_NT_APPS_proper_name 1073
#define IDH_NT_APPS_secondary_stress 1074
#define IDH_NT_APPS_silence_phonemes 1075
#define IDH_NT_APPS_syntactic_function_words 1076
#define IDH_NT_APPS__TAB_file 1077
#define IDH_NT_APPS_user_dictionary 1078
#define IDH_NT_APPS_user_dictionary_builder 1079
#define IDH_NT_APPS_voice_control_command 1080
#define IDH_NT_APPS_WAVE_file 1081
#define IDH_NT_APPS_wave_form_output 1082
#define IDH_NT_APPS_word_boundary 1083
#define IDH_NT_APPS_word_mode 1084
