extern	int main(int argc,char **argv );
extern	int find_base(void);
extern	void get_status(void);
extern	int set_status(struct dectalk_control *dtp);
extern	int get_data(void);
extern	int put_command(unsigned int cmd);
extern	void put_data(unsigned int data);
extern	unsigned short set_baud(unsigned short baudrate);
extern	short set_format(unsigned char bitsper,unsigned char parity,unsigned char stop);
extern	void flush_ring(struct serialring __far *ring);
extern	void un_xoff(void );
extern	unsigned short sense_xoff(void );
extern	unsigned char clear_ack(void );
extern	unsigned char get_ack(void );
extern	void check_is_bit(void );
extern	void enable_int(unsigned short vec);
extern	void disable_int(unsigned short vec);
extern	unsigned short dt_disable(void );
extern	unsigned short dt_getflags(void );
extern	void __far serial_init(void);
extern	void serial_close(void );
extern	unsigned short s_sendbuf(unsigned char __far *bufptr,unsigned short count);
extern	unsigned short p_sendbuf(unsigned char __far *bufptr,unsigned short count);
extern	unsigned short s_getbuf(unsigned char __far *bufptr,unsigned short count);
extern	unsigned short peek_outbuf(void);
extern	unsigned short peek_p_outbuf(void);
extern	unsigned short peek_inbuf(void);
extern	void __far __interrupt SerialHandler(void);
extern	void do_serial_int(void );
extern	void hitakey(void);
extern	unsigned int getpsp(void );
extern	void setpsp(unsigned int new_psp);
extern	void __far __interrupt dectalk_com(union INT_REGS int_frame);
extern	void __far __interrupt dectalk_lpt(union INT_REGS int_frame);
extern	void __far __interrupt multi_plex_int(union INT_REGS int_frame);
extern	void __far __interrupt multi_exit(void);
extern	int do_immd(unsigned int cmd,unsigned int data);
extern	int do_immd_nodata(unsigned int cmd);
extern	int do_immd_get(unsigned int cmd,unsigned int *data);
extern	int wait_dstat(unsigned int ticks);
extern	int check_dstat(void);
extern	int wait_cstat(int ticks);
extern	void __far __interrupt dectalk_timer(union INT_REGS int_frame);
extern	void sleep(unsigned short seconds);
extern	unsigned int do_a_flush(void);
extern	int wait_flush(void);
extern	void wait_reset(void);
extern	int parse_switch(int argc,char **argv );
extern	int usage(void);
extern	unsigned int atoh(char *s);
