/* XPM */
static char * dtk_windict_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 5 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	c #000000008080",
"X	s iconColor1	m black	c black",
"o	s iconColor6	m white	c yellow",
"O	c #808080808080",
/* pixels */
" ......  XXXXXX  XXXXXX         ",
" ...... XX     XX     XXXXXXXX  ",
" ..  ..        XX            X  ",
" ..  ..   XXXX XX            XXX",
" ...... X      XX XXXXX XXXX XoX",
" ......        XX            X X",
" ..  .. X XX X XX XX XX XXXX XoX",
" ..  ..        XX            X X",
" ..  .. X XXXX XX XXXXX X XX XoX",
"               XX            X X",
"XoX XXXXX X XX XX XXXXX XXXX XoX",
"XoX            XX            X X",
"X X XXXXX XXXX XX XXXXX XX X XoX",
"XoX            XX            X X",
"X X X XXX XX X XX X XXX XXXX XoX",
"XoX            XX            X X",
"X X XXXXX XXXX XX XXXXX XXXX XoX",
"XoX            XX            X X",
"X X XX XX XX X XX XXXXX X XX XoX",
"XoX            XX            X X",
"X X XXXXX XXXX XX XXXXX XXXX XoX",
"XoX            XX            XoX",
"X X X XXX XXXX XX XXXXX         ",
"XoX            XX        ...... ",
"X X XXXXX XXXX XX XXXX   ...... ",
"XoX            XX            .. ",
"X X XXX X      XX           ..  ",
"XoX            XX          ..   ",
"X X      XXXXXXXXXXXXXX   ..    ",
"XoXXXXXXXo o oXXXX o o X ..     ",
"X o o o oXXXXXXOOXXXXXXo ...... ",
"XXXXXXXXX     XXXX     X ...... "};
