/* XPM */
static char * dtk_windict_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 5 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	c #000000008080",
"X	s iconColor1	m black	c black",
"o	s iconColor6	m white	c yellow",
"O	c #808080808080",
/* pixels */
"  .........   XXXXXXXXX   XXXXXXXXX             ",
"  ......... XXX        XXX       XXXXXXXXXXXX   ",
"  ......... XXX        XXX       XXXXXXXXXXXX   ",
"  ...   ...            XXX                  X   ",
"  ...   ...    XXXXXX  XXX                  XXXX",
"  ...   ...    XXXXXX  XXX                  XXXX",
"  ......... XX         XXX XXXXXXXX XXXXXX  XooX",
"  .........            XXX                  X  X",
"  .........            XXX                  X  X",
"  ...   ... XX XXX  X  XXX XXX  XXX XXXXXX  XooX",
"  ...   ...            XXX                  X  X",
"  ...   ...            XXX                  X  X",
"  ...   ... XX XXXXXX  XXX XXXXXXXX XX XXX  XooX",
"                       XXX                  X  X",
"                       XXX                  X  X",
"XXoXX XXXXXXXX XX XXX  XXX XXXXXXXX XXXXXX  XooX",
"XXoXX                  XXX                  X  X",
"XXoXX                  XXX                  X  X",
"XX XX XXXXXXXX XXXXXX  XXX XXXXXXXX XXX  X  XooX",
"XXoXX                  XXX                  X  X",
"XXoXX                  XXX                  X  X",
"XX XX XX XXXXX XXX  X  XXX XX XXXXX XXXXXX  XooX",
"XXoXX                  XXX                  X  X",
"XXoXX                  XXX                  X  X",
"XX XX XXXXXXXX XXXXXX  XXX XXXXXXXX XXXXXX  XooX",
"XXoXX                  XXX                  X  X",
"XXoXX                  XXX                  X  X",
"XX XX XXX  XXX XXX  X  XXX XXXXXXXX XX XXX  XooX",
"XXoXX                  XXX                  X  X",
"XXoXX                  XXX                  X  X",
"XX XX XXXXXXXX XXXXXX  XXX XXXXXXXX XXXXXX  XooX",
"XXoXX                  XXX                  XooX",
"XXoXX                  XXX                  XooX",
"XX XX XX XXXXX XXXXXX  XXX XXXXXXXX             ",
"XXoXX                  XXX            ......... ",
"XXoXX                  XXX            ......... ",
"XX XX XXXXXXXX XXXXXX  XXX XXXXXX     ......... ",
"XXoXX                  XXX                  ... ",
"XXoXX                  XXX                  ... ",
"XX XX XXXXX XX         XXX                ...   ",
"XXoXX                  XXX               ...    ",
"XXoXX                  XXX               ...    ",
"XX XX         XXXXXXXXXXXXXXXXXXXXX    ...      ",
"XXoXXXXXXXXXXXo  o  oXXXXXX  o  o  X  ...       ",
"XXoXXXXXXXXXXXo  o  oXXXXXX  o  o  X  ...       ",
"XX oo oo oo ooXXXXXXXXXOOOXXXXXXXXXo  ......... ",
"XXXXXXXXXXXXXX       XXXXXX        X  ......... ",
"XXXXXXXXXXXXXX       XXXXXX        X  ......... "};
