NAME='DECtalk Development Kit V4.5'
CODE=DTK
VERS=460
MI=DTKDEV460.mi
ROOT=0
COMPRESS=1
RXMAKE=0
# subset definitions follow
%%
DTKDEVDOC460      .      2  'DECtalk Software V4.6 for Digital UNIX Development Documentation.'
DTKDEV460	  .	 2  'DECtalk Software V4.6 for Digital UNIX Development Kit.'
DTKDEVSAMP460	  .	 2  'DECtalk Software V4.6 for Digital UNIX Sample Programs.'
DTKDEVRELNOT460   .      2  'DECtalk Software V4.6 for Digital UNIX Release Notes.'
