NAME='DECtalk Development Kit V4.5'
CODE=DTK
VERS=461
MI=DTKDEV461.mi
ROOT=0
COMPRESS=1
RXMAKE=0
# subset definitions follow
%%
DTKDEVDOC461      .      2  'DECtalk Software V4.61 for Digital UNIX Development Documentation.'
DTKDEV461	  .	 2  'DECtalk Software V4.61 for Digital UNIX Development Kit.'
DTKDEVSAMP461	  .	 2  'DECtalk Software V4.61 for Digital UNIX Sample Programs.'
DTKDEVRELNOT461   .      2  'DECtalk Software V4.61 for Digital UNIX Release Notes.'
