NAME='DECtalk Development Kit V4.5'
CODE=DTK
VERS=450
MI=DTKDEV450.mi
ROOT=0
COMPRESS=1
RXMAKE=0
# subset definitions follow
%%
DTKDEVDOC450      .      2  'DECtalk Software V4.5 for Digital UNIX Development Documentation.'
DTKDEV450	  .	 2  'DECtalk Software V4.5 for Digital UNIX Development Kit.'
DTKDEVSAMP450	  .	 2  'DECtalk Software V4.5 for Digital UNIX Sample Programs.'
DTKDEVRELNOT450   .      2  'DECtalk Software V4.5 for Digital UNIX Release Notes.'
