BASE_DIR="/usr/local"

LIBS=$BASE_DIR"/lib"
DICTIONARIES=$BASE_DIR"/lib/DECtalk/"
TEXT_SAMPLE_PROGRAMS=$BASE_DIR"/bin"
GRAPHIC_SAMPLE_PROGRAMS=$BASE_DIR"/X11/bin"
SAMPLE_SOURCE=$BASE_DIR"/src/DECtalk"
MAN1=$BASE_DIR"/man/man1"
MAN3=$BASE_DIR"/man/man3"
DOCUMENTATION=$BASE_DIR"/doc/DECtalk"
BITMAPS=$BASE_DIR"/lib/DECtalk/bitmaps"


