/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for DECtalk.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
** Programmer's Guide
**    Introduction to DECtalk Software (NT_APPS)
**    Using the Programming Applets to Learn DECtalk Software Basics (NT_APPS)
**    Introduction to the DECtalk Software API (SDK_1)
**    How to do Multi-Language Programming (SDK_1)
**
** Reference Guide
**    DECtalk Software API Calls (SDK_2)
**    DECtalk Software In-Line Commands (REF_1)
**    Using In-Line Commands (REF_2)
**    DECtalk Software Reference Tables (REF_3)
**    Customizing a DECtalk Software Voice (SDK_3)
**    Shared Memory Initialization Technique(SMIT) and Access32 (SDK_3)
**
*/

#define IDH_MAIN_INDEX 1
#define What_s_New_in_DECtalk_V4_61	2
#define What_s_New_in_DECtalk_Software_V4.6	4
