/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for REF_2.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_REF_2_Using_In_Line_Commands 4501
#define IDH_REF_2_Changing_Rhythm_Stress_and_Intonation 4502
#define IDH_REF_2_Developing_an_Electronic_Mail_Reading_Application 4503
#define IDH_REF_2_Example_of_the_use_of_pauses_in_numerical_strings 4504
#define IDH_REF_2_Optimizing_the_Quality_of_Spoken_Text 4505
#define IDH_REF_2_Index_Marks_for_Speech_Status 4506
#define IDH_REF_2_Speaking_Rate 4507
#define IDH_REF_2_Adjusting_Period_and_Comma_Pause_Durations 4508
#define IDH_REF_2_Text_Tuning_Example 4509
#define IDH_REF_2_Avoiding_Common_Errors 4510
