/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for REF_1.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_REF_1_DECtalk_Software_In_Line_Commands_Overview 4001
#define IDH_REF_1_Comma_Pause_comma 4002
#define IDH_REF_1_Dial_Tones_dial 4003
#define IDH_REF_1_Error_error 4004
#define IDH_REF_1_Index_Mark_index_mark 4005
#define IDH_REF_1_Log_log 4006
#define IDH_REF_1_Mode_mode 4007
#define IDH_REF_1_Europe_Mode_Example 4008
#define IDH_REF_1_Math_Mode_Example 4009
#define IDH_REF_1_Name_Mode_Example 4010
#define IDH_REF_1_Voice_Selection_voice 4011
#define IDH_REF_1_Period_Pause_period 4012
#define IDH_REF_1_Phoneme_Interpretation_phoneme 4013
#define IDH_REF_1_Play_Wave_Files_play 4014
#define IDH_REF_1_Pronounce_pron 4015
#define IDH_REF_1_Punctuation_punc 4016
#define IDH_REF_1_Rate_Selection_rate 4017
#define IDH_REF_1_Say_say 4018
#define IDH_REF_1_Skip_skip_XX 4019
#define IDH_REF_1_Sync_sync 4020
#define IDH_REF_1_Tone_tone 4021
#define IDH_REF_1_Volume_volume 4022
#define IDH_REF_1_Monaural_Volume_Control 4023
#define IDH_REF_1_Stereo_Volume_Control 4024
#define Email_Mode_Example 4025
#define Pitch_pitch 4027
#define Dial_Tones_dial 4028
