/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for REF_3.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_REF_3_DECtalk_Software_Reference_Tables 5001
#define IDH_REF_3_Phonemic_Symbols 5002
#define IDH_REF_3_Phonemic_Symbols_2 5003
#define IDH_REF_3_Stress_and_Syntactic_Symbols 5004
#define IDH_REF_3_Stress_Symbols 5005
#define IDH_REF_3_Syntactic_Symbols 5006
#define IDH_REF_3_Tone_Table 5007
#define IDH_REF_3_Phonemic_Syntax_for_Singing 5008
#define IDH_REF_3_Tone_Table_2 5009
#define IDH_REF_3_DECtalk_Software_Singing_Happy_Birthday 5010
#define IDH_REF_3_Homographs 5011
#define IDH_REF_3_Homograph_Phonetics_A 5012
#define IDH_REF_3_Homograph_Phonetics_B_C 5013
#define IDH_REF_3_Homograph_Phonetics_D_G 5014
#define IDH_REF_3_Homograph_Phonetics_I_L 5015
#define IDH_REF_3_Homograph_Phonetics_M_P 5016
#define IDH_REF_3_Homograph_Phonetics_R 5017
#define IDH_REF_3_Homograph_Phonetics_S_W 5018
#define Phonemes_in_Unicode_Sequence 5019
#define Supported_SAPI_functions 5020
#define Supported_SAPI_Version_5_Features	5021
#define Phonemic_Symbols_U_K_English	5022
#define Phonemic_Symbols_Castilian_Spanish	5023
#define Phonemic_Symbols_Latin_American_Spanish	5024
#define Phonemic_Symbols_German	5025
#define Phonemic_Symbols_French	5026
