/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for SDK_3.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_SDK_3_Customizing_a_DECtalk_Software_Voice 3501
#define IDH_SDK_3_Design_Voice_dv 3502
#define IDH_SDK_3_Definitions_of_DECtalk_Software_Voices 3503
#define IDH_SDK_3_Changing_Gender_and_Head_Size 3504
#define IDH_SDK_3_Sex_sx 3505
#define IDH_SDK_3_Head_Size_hs 3506
#define IDH_SDK_3_Higher_Formants_f4_f5_b4_and_b5 3507
#define IDH_SDK_3_Changing_Voice_Quality 3508
#define IDH_SDK_3_Breathiness_br 3509
#define IDH_SDK_3_Lax_Breathiness_lx 3510
#define IDH_SDK_3_Smoothness_sm 3511
#define IDH_SDK_3_Richness_ri 3512
#define IDH_SDK_3_Nopen_Fixed_nf 3513
#define IDH_SDK_3_Laryngealization_la 3514
#define IDH_SDK_3_Changing_Pitch_and_Intonation 3515
#define IDH_SDK_3_Baseline_Fall_bf 3516
#define IDH_SDK_3_Hat_Rise_hr 3517
#define IDH_SDK_3_Stress_Rise_sr 3518
#define IDH_SDK_3_Assertiveness_as 3519
#define IDH_SDK_3_Quickness_qu 3520
#define IDH_SDK_3_Average_Pitch_ap_and_Pitch_Range_pr 3521
#define IDH_SDK_3_Changing_Relative_Gains_and_Avoiding_Overloads 3522
#define IDH_SDK_3_Loudness_g5 3523
#define IDH_SDK_3_Sound_Source_Gains_gv_gh_gf_and_gn 3524
#define IDH_SDK_3_Cascade_Vocal_Tract_Gains_g1_g2_g3_and_g4 3525
#define IDH_SDK_3_Saving_Changes_to_Val_s_Voice 3526
#define IDH_SDK_3_Save_save 3527

