/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for SDK_4.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define Preprocessor_Rules_for_Parsing 5501
#define Parsing_Email 5502
#define Parsing_Punctuation 5503
#define Interpreting_Punctuation_Marks_as_Words 5504
#define Interpreting_Punctuation_Marks_as_Punctuation 5505
#define General_Parsing_Rules 5506
#define German 5507
#define Spanish_Castilian_and_Latin_American 5508
#define English_UK 5509
#define English_US_UK 5510
#define Email 5511
#define Rules 5512
#define Punctuation 5513
