/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for SDK_1.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_SDK_1_Introduction_to_the_DECtalk_Software_API 2001
#define IDH_SDK_1_Core_API_Functions_1 2002
#define IDH_SDK_1_Audio_Output_Control_Functions_1 2003
#define IDH_SDK_1_Blocking_Synchronization_Function_1 2004
#define IDH_SDK_1_Control_and_Status_Functions_1 2005
#define IDH_SDK_1_Special_Text_To_Speech_Modes_1 2006
#define IDH_SDK_1_Loading_and_Unloading_a_User_Dictionary_1 2007
#define IDH_SDK_1_The_Core_API_Functions 2008
#define IDH_SDK_1_Controlling_Queuing_with_Flags 2009
#define IDH_SDK_1_Important_Text_Queuing_Information 2010
#define IDH_SDK_1_Clause_Based_Synthesis 2011
#define IDH_SDK_1_Callback_Routines_and_Window_Procedures 2012
#define IDH_SDK_1_Error_Messages 2013
#define IDH_SDK_1_Index_Mark_Messages 2014
#define IDH_SDK_1_Buffer_Messages 2015
#define IDH_SDK_1_Callback_Routine_Example 2016
#define IDH_SDK_1_Window_Procedure_Example 2017
#define IDH_SDK_1_Audio_Output_Control_Functions 2018
#define IDH_SDK_1_Blocking_Synchronization_Function 2019
#define IDH_SDK_1_Control_and_Status_Functions 2020
#define IDH_SDK_1_Special_Text_To_Speech_Modes 2021
#define IDH_SDK_1_Wave_File_Mode 2022
#define IDH_SDK_1_Log_File_Mode 2023
#define IDH_SDK_1_Speech_To_Memory_Mode 2024
#define IDH_SDK_1_Initialization_of_Memory_Buffers 2025
#define IDH_SDK_1_TTS_BUFFER_T_Structure_ttsapi_h 2026
#define IDH_SDK_1_TTS_PHONEME_T_Structure_ttsapi_h 2027
#define IDH_SDK_1_TTS_INDEX_T_Structure_ttsapi_h 2028
#define IDH_SDK_1_Return_of_Memory_Buffers 2029
#define IDH_SDK_1_Dictionary_Functions_UNIX_only 2030
#define IDH_SDK_1_Creating_a_User_Dictionary 2031
#define IDH_SDK_1_Loading_of_the_Main_Pronunciation_Dictionary 2032
#define IDH_SDK_1_Loading_of_the_User_Dictionary 2033
#define IDH_SDK_1_Dictionary_Functions_Windows_only 2034
#define IDH_SDK_1_Creating_a_User_Dictionary_2 2035
#define IDH_SDK_1_Loading_the_Main_Pronunciation_Dictionary 2036
#define IDH_SDK_1_Loading_the_User_Dictionary 2037
#define IDH_SDK_1_Sample_Programs_UNIX_only 2038
#define IDH_SDK_1_Building_Sample_Programs 2039
#define IDH_SDK_1_Header_Files 2040
#define IDH_SDK_1_Shareable_Libraries 2041
#define IDH_SDK_1_Sample_Programs_Windows_only 2042
#define How_to_do_Multi_Language_Programming 2043
#define Starting_a_language 2044
#define Selecting_a_Language 2045
#define Closing_a_language 2046
#define Multi_Language_Programming_Example 2047
#define Phoneme_Notifications 2048
#define Phoneme_Identifiers_and_Phonemic_Symbols_English 2049
#define Loading_the_Main_Dictionary_Static_Engine 2050
#define Registry_Entry_Information 2051
#define TTS_CAPS_T_Structure_ttsapi.h 2052
#define TTS_CAPS_T_Structure_ttsapi.h 2052
#define TTS_CAPS_T_Structure_ttsapi.h 2052
#define TTS_CAPS_T_Structure_ttsapi.h 2052
#define TTS_CAPS_T_Structure_ttsapi.h 2052
#define TTS_CAPS_T_Structure_ttsapi.h 2052
#define TTS_CAPS_T_Structure_ttsapi.h 2052
#define TTS_CAPS_T_Structure_ttsapi.h 2052
#define TTS_CAPS_T_Structure_ttsapi.h 2052
