/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
** Help Context Identifiers for SDK_2.hh
** Generated by RoboHELP
** 
** RoboHELP observes a polite protocol for dealing with this file.
** It will add new identifiers for new Topic IDs that are
** added to the RTF file with the same name.
** 
** RoboHELP will also preserve comments which are placed in this
** file, so documentation staff can insert notes to those crazy
** developers and vice versa. 
** 
** However, the numeric values of the identifiers are stored only
** in this file.  Therefore, if you change the numeric value here,
** it is changed for good.  RoboHELP will not try to change it back.
**
** Normally, RoboHELP will remove the symbols for Topic IDs
** which have been removed from the .RTF file.  However, you can
** set a checkbox in your project setup to prevent RoboHELP from
** doing this.  You may want to do this and make use of the Alias
** capability of the help compiler.
**
*/

#define IDH_SDK_2_DECtalk_Software_API_Function_Calls 3001
#define IDH_SDK_2_TextToSpeechAddBuffer 3002
#define IDH_SDK_2_TextToSpeechCloseInMemory 3003
#define IDH_SDK_2_TextToSpeechCloseLogFile 3004
#define IDH_SDK_2_TextToSpeechCloseWaveOutFile 3005
#define IDH_SDK_2_TextToSpeechGetCaps 3006
#define IDH_SDK_2_TextToSpeechGetLanguage 3007
#define IDH_SDK_2_TextToSpeechGetRate 3008
#define IDH_SDK_2_TextToSpeechGetSpeaker 3009
#define IDH_SDK_2_TextToSpeechGetStatus 3010
#define IDH_SDK_2_TextToSpeechLoadUserDictionary 3011
#define IDH_SDK_2_TextToSpeechOpenInMemory 3012
#define IDH_SDK_2_TextToSpeechOpenLogFile 3013
#define IDH_SDK_2_TextToSpeechOpenWaveOutFile 3014
#define IDH_SDK_2_TextToSpeechPause 3015
#define IDH_SDK_2_TextToSpeechReset 3016
#define IDH_SDK_2_TextToSpeechResume 3017
#define IDH_SDK_2_TextToSpeechReturnBuffer 3018
#define IDH_SDK_2_TextToSpeechSetLanguage 3019
#define IDH_SDK_2_TextToSpeechSetRate 3020
#define IDH_SDK_2_TextToSpeechSetSpeaker 3021
#define IDH_SDK_2_TextToSpeechShutdown 3022
#define IDH_SDK_2_TextToSpeechSpeak 3023
#define IDH_SDK_2_TextToSpeechStartup_Windows_only 3024
#define IDH_SDK_2_TextToSpeechStartup_UNIX_only 3025
#define IDH_SDK_2_TextToSpeechStartupEx 3026
#define IDH_SDK_2_TextToSpeechSync 3027
#define IDH_SDK_2_TextToSpeechUnloadUserDictionary 3028
#define IDH_SDK_2_TextToSpeechVersion 3029
#define IDH_INPUT_CHARACTER_COUNT_0_ttsapi_h 3030
#define IDH_STATUS_SPEAKING_1_ttsapi_h 3031
#define IDH_WAVE_OUT_DEVICE_ID_2_ttsapi_h 3032
#define IDH_Paul_0_ttsapi_h 3033
#define IDH_HARRY_2_ttsapi_h 3034
#define IDH_FRANK_3_ttsapi_h 3035
#define IDH_DENNIS_4_ttsapi_h 3036
#define IDH_BETTY_1_ttsapi_h 3037
#define IDH_URSULA_6_ttsapi_h 3038
#define IDH_WENDY_8_ttsapi_h 3039
#define IDH_RITA_7_ttsapi_h 3040
#define IDH_KIT_5_ttsapi_h 3041
#define IDH_WAVE_FORMAT_1M08_0X00000001_mmsystem_h 3042
#define IDH_WAVE_FORMAT_1M16_0X00000004_mmsystem 3043
#define IDH_WAVE_FORMAT_08M08_0x00001000_ttsapi_h 3044
#define IDH_LOG_TEXT_0X00000001_ttsapi_h 3045
#define IDH_LOG_PHONEMES_0X00000002_ttsapi_h 3046
#define IDH_LOG_SYLLABLES_0X00000010_ttsapi_h 3047
#define IDH_FALSE_0 3048
#define IDH_TRUE_1 3049
#define IDH_TTS_FORCE_0x00000001_ttsapi_h 3050
#define IDH_typedef_DWORD_LANGUAGE_T_ttsapi_h 3051
#define IDH_TTS_NORMAL_0x00000000_ttsapi_h 3052
#define IDH_OWN_AUDIO_DEVICE_0x00000001_ttsapi_h 3053
#define IDH_REPORT_OPEN_ERROR_0x00000002_ttsapi_h 3054
#define IDH_DO_NOT_USE_AUDIO_DEVICE_0x80000000_ttsapi_h 3055
#define IDH_SDK_2_TTS_CAPS_T_Structure_ttsapi_h 3056
#define IDH_SDK_2_The_LANGAUGE_PARAMS_T_Structure_ttsapi_h 3057
#define IDH_SDK_2_TTS_AMERICAN_ENGLISH_1_ttsapi_h 3058
#define IDH_SDK_2_PROPER_NAME_PRONUNCIATION_0x00000001_ttsapi_h 3059
#define IDH_SDK_2_TTS_FORCE_0x00000001_ttsapi_h_2 3060
#define IDH_SDK_2_typedef_DWORD_LANGUAGE_T_ttsapi_h 3061
#define IDH_SDK_2_typedef_DWORD_SPEAKER_T_ttsapi_h 3062
#define TextToSpeechCloseLang 3063
#define TextToSpeechEnumLangs 3064
#define TextToSpeechGetFeatures 3065
#define TextToSpeechSelectLang 3066
#define TextToSpeechStartLang 3067
#define TextToSpeechTyping 3068
#define TextToSpeechVersionEx 3069
