extern	void iso_case_map(void );
extern	void dectalk_main(void );
extern	void __far serial_init(void);
extern	void __far serial_task(void);
extern	void __far slflush(void);
extern	void __far SerialHandler(void);
extern	void SHPutRing(unsigned char inchar);
extern	void SHPutPRing(unsigned char outchar);
extern	unsigned short SHSerialUpdate(void);
extern	unsigned long ReadRom(unsigned long start,unsigned long count,unsigned char __far *buff);
extern	unsigned int __pascal __far DReadBuff(char __far *buff,unsigned short __far *size);
extern	void __pascal __far DWriteBuff(char __far *buff,unsigned short __far *size);
extern	void mystrcat(unsigned char __far *dest,unsigned char __far *src,unsigned int count);
extern	int loader_task(void);
extern	unsigned short __far get__ss(void);
extern	unsigned short __far get__ds(void);
extern	unsigned short __far get__es(void);
extern	int __far isa_task(void);
extern	void put_data(unsigned int data);
extern	void __far module_check(void);
extern	void enable_int(unsigned char intmask);
extern	void disable_int(unsigned char intmask);
extern	short set_baud(unsigned short baudrate);
extern	short set_format(unsigned char bitsper,unsigned char parity,unsigned char stop);
extern	void init_spc(void );
extern	int __far spc_task(void);
extern	int __far index_task(void);
extern	int __far dgt_task(void);
extern	void dma_init(void);
extern	void serial_send_index(unsigned short data);
extern	void do_beep(void );
